name: build_test_data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  build_test_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build

      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          ref: "main"
          token: "${{ secrets.REPO_DATA_TOKEN }}"

      - name: build_test_data
        run: |
          export PYTHONPATH="$PYTHONPATH:./src"
          python workflows/build_test_data.py

      - name: Push to github repo
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

          git pull origin main
          
          echo "* $(date) build_test_data"
          echo "* $(date) build_test_data" >> update.txt
          
          git add .
          git commit -m "build_test_data $(date)"
          git push origin main
